# Generated by Django 5.0.6 on 2024-06-06 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai/')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2024, 6, 6, 14, 48, 43, 675045, tzinfo=datetime.timezone.utc))),
                ('type', models.CharField(choices=[('GR', 'GINGER'), ('ML', 'MASALA')], max_length=2)),
            ],
        ),
    ]
